import type { SpotlightOpportunityDefinition } from '../../../types/spotlight/opportunity';

/** Central opportunity registry — Publisher Success Coach messages (Phase 5.5) */
export const SPOTLIGHT_OPPORTUNITY_REGISTRY: SpotlightOpportunityDefinition[] = [
  // Content Quality
  { id: 'missing_hero', title: 'Missing Hero', description: 'No headline or hero section', coachingMessage: 'Add a compelling headline that tells visitors what this experience is about within 3 seconds.', category: 'content_quality', severity: 'high', priority: 'high', owner: 'publisher', suggestedAction: 'Add heading block', estimatedImpactPercent: 12, effort: 'low', futureAiCapability: 'optimize_headline', auditRuleId: 'content.hero' },
  { id: 'missing_thumbnail', title: 'Missing Thumbnail', description: 'No primary media attached', coachingMessage: 'Campaigns with strong hero images typically see higher click-through in Spotlight carousel and homepage placements.', category: 'media', severity: 'high', priority: 'high', owner: 'publisher', suggestedAction: 'Upload hero image', estimatedImpactPercent: 18, effort: 'low', auditRuleId: 'media.thumbnail' },
  { id: 'missing_video', title: 'Missing Video', description: 'No video content', coachingMessage: 'Video experiences often drive 2× longer engagement. Consider adding a product demo, creator review, or brand story.', category: 'media', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Add video block', estimatedImpactPercent: 22, effort: 'medium', auditRuleId: 'media.video' },
  { id: 'missing_gallery', title: 'Missing Gallery', description: 'No image gallery', coachingMessage: 'A gallery helps visitors explore your product or experience visually before they buy.', category: 'media', severity: 'low', priority: 'low', owner: 'publisher', suggestedAction: 'Add gallery block', estimatedImpactPercent: 8, effort: 'low', auditRuleId: 'media.gallery' },
  { id: 'missing_comparison', title: 'Missing Comparison', description: 'No comparison table', coachingMessage: 'Help buyers decide faster by comparing options side-by-side — especially effective for electronics and buying guides.', category: 'content_quality', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Add comparison table', estimatedImpactPercent: 15, effort: 'medium', auditRuleId: 'content.comparison' },
  { id: 'missing_guide', title: 'Missing Guide Content', description: 'No educational blocks', coachingMessage: 'Educational content builds trust. Add a checklist, FAQ, or buying guide section to help visitors make confident decisions.', category: 'content_quality', severity: 'low', priority: 'low', owner: 'publisher', suggestedAction: 'Add guide blocks', estimatedImpactPercent: 10, effort: 'medium', auditRuleId: 'content.guide' },
  { id: 'missing_review', title: 'Missing Review Content', description: 'No review or pros/cons', coachingMessage: 'Reviews and pros/cons blocks increase buyer confidence. Consider adding creator or editorial review content.', category: 'content_quality', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Add review block', estimatedImpactPercent: 14, effort: 'medium', auditRuleId: 'content.review' },
  // Commerce
  { id: 'missing_products', title: 'Missing Products', description: 'No products linked', coachingMessage: 'Link products to make this Spotlight experience shoppable. Shoppable content drives measurable commerce outcomes.', category: 'commerce', severity: 'critical', priority: 'critical', owner: 'publisher', suggestedAction: 'Link products', estimatedImpactPercent: 35, effort: 'low', futureAiCapability: 'suggest_products', auditRuleId: 'commerce.products' },
  { id: 'missing_cta', title: 'Missing CTA', description: 'No call-to-action', coachingMessage: 'Add a "Shop Now" or "Compare Products" button to help visitors continue their buying journey.', category: 'commerce', severity: 'high', priority: 'high', owner: 'publisher', suggestedAction: 'Add CTA block', estimatedImpactPercent: 20, effort: 'low', futureAiCapability: 'suggest_cta', auditRuleId: 'commerce.cta' },
  { id: 'missing_buy_button', title: 'Missing Buy Button', description: 'No buy now action', coachingMessage: 'A clear Buy Now button reduces friction at the moment of purchase intent.', category: 'commerce', severity: 'high', priority: 'high', owner: 'publisher', suggestedAction: 'Add buy button', estimatedImpactPercent: 18, effort: 'low', auditRuleId: 'commerce.buy' },
  { id: 'missing_compare', title: 'Missing Compare', description: 'No compare action', coachingMessage: 'Enable Compare so visitors can evaluate options — a key step in Choosify\'s decision journey.', category: 'commerce', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Enable compare', estimatedImpactPercent: 12, effort: 'low', auditRuleId: 'commerce.compare' },
  { id: 'missing_wishlist', title: 'Missing Wishlist', description: 'No wishlist integration', coachingMessage: 'Wishlist lets visitors save products for later, increasing return visits and conversion over time.', category: 'commerce', severity: 'low', priority: 'low', owner: 'publisher', suggestedAction: 'Enable wishlist', estimatedImpactPercent: 6, effort: 'low', auditRuleId: 'commerce.wishlist' },
  { id: 'missing_offers', title: 'Missing Offers', description: 'No offer or coupon block', coachingMessage: 'Limited-time offers create urgency. Consider adding an offer block for promotions and launches.', category: 'commerce', severity: 'medium', priority: 'medium', owner: 'brand', suggestedAction: 'Add offer block', estimatedImpactPercent: 16, effort: 'low', auditRuleId: 'commerce.offers' },
  { id: 'missing_cross_sell', title: 'Cross-sell Opportunity', description: 'Related products not linked', coachingMessage: 'Link accessories and related products to increase average order value from Spotlight traffic.', category: 'commerce', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Add related products', estimatedImpactPercent: 14, effort: 'medium', futureAiCapability: 'suggest_products', auditRuleId: 'commerce.cross_sell' },
  { id: 'missing_bundle', title: 'Bundle Opportunity', description: 'No bundle block', coachingMessage: 'Product bundles often convert better than single items. Group complementary products together.', category: 'commerce', severity: 'low', priority: 'low', owner: 'publisher', suggestedAction: 'Add bundle block', estimatedImpactPercent: 10, effort: 'medium', auditRuleId: 'commerce.bundle' },
  // SEO
  { id: 'missing_seo', title: 'Missing SEO', description: 'SEO panel incomplete', coachingMessage: 'Complete your SEO settings so Spotlight content ranks in search and social shares look professional.', category: 'seo', severity: 'high', priority: 'high', owner: 'publisher', suggestedAction: 'Open SEO panel', estimatedImpactPercent: 15, effort: 'low', futureAiCapability: 'improve_seo', auditRuleId: 'seo.basic' },
  { id: 'missing_meta', title: 'Missing Meta Description', description: 'No meta description', coachingMessage: 'A clear meta description improves click-through from search results and social previews.', category: 'seo', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Add meta description', estimatedImpactPercent: 8, effort: 'low', futureAiCapability: 'improve_seo', auditRuleId: 'seo.meta' },
  { id: 'missing_schema', title: 'Missing Schema', description: 'No structured data type', coachingMessage: 'Schema markup helps search engines understand your content type — Article, Product, Event, or Video.', category: 'seo', severity: 'low', priority: 'low', owner: 'publisher', suggestedAction: 'Set schema type', estimatedImpactPercent: 5, effort: 'low', auditRuleId: 'seo.schema' },
  // Discovery
  { id: 'missing_tags', title: 'Missing Tags', description: 'No discovery tags', coachingMessage: 'Increase discoverability by adding 3–5 relevant tags. Campaigns with complete tagging typically perform better in search and Spotlight recommendations.', category: 'discovery', severity: 'high', priority: 'high', owner: 'publisher', suggestedAction: 'Add tags', estimatedImpactPercent: 18, effort: 'low', futureAiCapability: 'suggest_tags', auditRuleId: 'discovery.tags' },
  { id: 'missing_categories', title: 'Missing Categories', description: 'No category links', coachingMessage: 'Link categories so your content appears in relevant category pages and filters.', category: 'discovery', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Link categories', estimatedImpactPercent: 12, effort: 'low', auditRuleId: 'discovery.categories' },
  { id: 'missing_collections', title: 'Missing Collection', description: 'Not in a collection', coachingMessage: 'Collections group related experiences. Add this content to a collection for curated discovery surfaces.', category: 'discovery', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Add to collection', estimatedImpactPercent: 10, effort: 'low', futureAiCapability: 'suggest_collection', auditRuleId: 'discovery.collections' },
  { id: 'missing_series', title: 'Missing Series', description: 'Not part of a series', coachingMessage: 'Series build returning audiences. Connect episodic content for binge-style discovery.', category: 'discovery', severity: 'low', priority: 'low', owner: 'publisher', suggestedAction: 'Add to series', estimatedImpactPercent: 8, effort: 'low', futureAiCapability: 'suggest_series', auditRuleId: 'discovery.series' },
  { id: 'missing_featured', title: 'Not Featured', description: 'Not marked featured', coachingMessage: 'Featured content gets priority placement on homepage and Spotlight carousel.', category: 'discovery', severity: 'low', priority: 'low', owner: 'brand', suggestedAction: 'Mark featured', estimatedImpactPercent: 14, effort: 'low', auditRuleId: 'discovery.featured' },
  { id: 'missing_related', title: 'Missing Related Content', description: 'No related Spotlight links', coachingMessage: 'Link related guides, reviews, and campaigns to keep visitors exploring your Spotlight ecosystem.', category: 'discovery', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Add related content', estimatedImpactPercent: 11, effort: 'medium', auditRuleId: 'discovery.related' },
  // Creator & Brand
  { id: 'missing_creator', title: 'Missing Creator', description: 'No creator collaboration', coachingMessage: 'Creator collaborations often drive higher trust and engagement. Consider partnering with a relevant creator.', category: 'creator', severity: 'medium', priority: 'medium', owner: 'brand', suggestedAction: 'Invite creator', estimatedImpactPercent: 20, effort: 'high', futureAiCapability: 'suggest_creator', auditRuleId: 'creator.collaboration' },
  { id: 'missing_brand', title: 'Missing Brand Link', description: 'No brand associated', coachingMessage: 'Link your brand so this content surfaces on your brand page and builds brand authority.', category: 'brand', severity: 'medium', priority: 'medium', owner: 'brand', suggestedAction: 'Link brand', estimatedImpactPercent: 10, effort: 'low', auditRuleId: 'brand.link' },
  // Trust & Health
  { id: 'low_trust', title: 'Low Trust Score', description: 'Trust signals below threshold', coachingMessage: 'Complete verification and add creator credentials to improve trust with Choosify buyers.', category: 'trust', severity: 'high', priority: 'high', owner: 'publisher', suggestedAction: 'Improve trust signals', estimatedImpactPercent: 12, effort: 'medium', auditRuleId: 'trust.score' },
  { id: 'stale_content', title: 'Stale Content', description: 'Not updated recently', coachingMessage: 'Fresh content ranks higher in discovery. Update media, products, or copy to signal active publishing.', category: 'health', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Refresh content', estimatedImpactPercent: 9, effort: 'medium', auditRuleId: 'health.freshness' },
  { id: 'missing_localization', title: 'Missing Localization', description: 'Single language only', coachingMessage: 'Localize for key markets to expand reach. Phase 5.6 Emi can help translate automatically.', category: 'localization', severity: 'low', priority: 'low', owner: 'brand', suggestedAction: 'Add localization', estimatedImpactPercent: 8, effort: 'high', futureAiCapability: 'translate', auditRuleId: 'localization.missing' },
  { id: 'accessibility_gaps', title: 'Accessibility Gaps', description: 'Alt text or structure incomplete', coachingMessage: 'Add alt text to images and use heading hierarchy for screen readers — good for SEO and inclusivity.', category: 'accessibility', severity: 'medium', priority: 'medium', owner: 'publisher', suggestedAction: 'Fix accessibility', estimatedImpactPercent: 5, effort: 'low', auditRuleId: 'accessibility.alt' },
  { id: 'missing_live', title: 'Missing Live Experience', description: 'No live or replay block', coachingMessage: 'Live events create urgency and real-time commerce. Consider a launch event or product demo stream.', category: 'content_quality', severity: 'low', priority: 'low', owner: 'brand', suggestedAction: 'Plan live event', estimatedImpactPercent: 25, effort: 'high', auditRuleId: 'content.live' },
  { id: 'expiring_campaign', title: 'Expiring Soon', description: 'Campaign ends within 7 days', coachingMessage: 'This campaign expires soon. Extend the schedule or create a follow-up experience to maintain momentum.', category: 'publishing', severity: 'high', priority: 'high', owner: 'publisher', suggestedAction: 'Extend schedule', estimatedImpactPercent: 0, effort: 'low', auditRuleId: 'publishing.expiring' },
  { id: 'ai_readiness_low', title: 'AI Readiness Low', description: 'Metadata incomplete for Emi', coachingMessage: 'Complete blocks, SEO, and product links now — Phase 5.6 Emi will use this structure to auto-optimize.', category: 'ai_readiness', severity: 'info', priority: 'low', owner: 'publisher', suggestedAction: 'Complete metadata', estimatedImpactPercent: 0, effort: 'medium', auditRuleId: 'ai.readiness' },
];

export function getOpportunityDefinition(id: string): SpotlightOpportunityDefinition | undefined {
  return SPOTLIGHT_OPPORTUNITY_REGISTRY.find((o) => o.id === id);
}

export function opportunitiesByCategory(category: SpotlightOpportunityDefinition['category']): SpotlightOpportunityDefinition[] {
  return SPOTLIGHT_OPPORTUNITY_REGISTRY.filter((o) => o.category === category);
}

export const OPPORTUNITY_TYPE_COUNT = SPOTLIGHT_OPPORTUNITY_REGISTRY.length;
